// Package html renders a Document as a single self-contained HTML file.
//
// The output has zero external dependencies — no CDN, no web fonts, no network
// calls — so it works in air-gapped environments. The scan data is embedded as
// a JSON island and rendered client-side by a small vanilla-JS script. (The
// interactive vis.js graph is a v0.2 deliverable; this report groups, filters,
// and summarises the same graph.)
package html

import (
	"encoding/json"
	"io"
	"strings"

	"github.com/Aakhri-Pastaa/infrasight/internal/output"
)

// Render writes a self-contained HTML report for the document.
func Render(w io.Writer, doc output.Document) error {
	// MarshalIndent escapes <, > and & (SetEscapeHTML is on by default), so the
	// payload is safe to embed inside a <script type="application/json"> island.
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	out := strings.Replace(page, dataToken, string(data), 1)
	_, err = io.WriteString(w, out)
	return err
}

const dataToken = "/*__INFRASIGHT_DATA__*/"

const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>InfraSight Report</title>
<style>
:root{
  --bg:#0f1419; --panel:#1a212b; --panel2:#222b38; --fg:#e6edf3; --muted:#8b98a8;
  --border:#2b3543; --accent:#4f9cf9;
  --ok:#3fb950; --warn:#d29922; --crit:#f85149;
}
@media (prefers-color-scheme: light){
  :root{ --bg:#f6f8fa; --panel:#fff; --panel2:#f0f3f6; --fg:#1f2328; --muted:#636c76;
         --border:#d0d7de; --accent:#0969da; }
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
  font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
header{padding:20px 24px;border-bottom:1px solid var(--border);background:var(--panel)}
header h1{margin:0;font-size:18px;letter-spacing:.3px}
header .sub{color:var(--muted);font-size:13px;margin-top:4px}
.wrap{max-width:1100px;margin:0 auto;padding:20px 24px}
.cards{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:18px}
.card{background:var(--panel);border:1px solid var(--border);border-radius:10px;
  padding:14px 16px;min-width:120px;flex:1}
.card .n{font-size:24px;font-weight:600}
.card .l{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.5px}
.crit .n{color:var(--crit)} .warn .n{color:var(--warn)} .ok .n{color:var(--ok)}
.controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:16px}
.controls input[type=search]{flex:1;min-width:220px;padding:8px 12px;border-radius:8px;
  border:1px solid var(--border);background:var(--panel);color:var(--fg)}
.types{display:flex;gap:8px;flex-wrap:wrap}
.chip{font-size:12px;padding:4px 10px;border-radius:999px;border:1px solid var(--border);
  background:var(--panel);cursor:pointer;user-select:none}
.chip.off{opacity:.4}
.group{margin-bottom:14px;border:1px solid var(--border);border-radius:10px;overflow:hidden}
.group>summary{cursor:pointer;padding:10px 14px;background:var(--panel);font-weight:600;
  list-style:none;display:flex;justify-content:space-between;align-items:center}
.group>summary::-webkit-details-marker{display:none}
.count{color:var(--muted);font-weight:400;font-size:12px}
.node{display:flex;gap:10px;align-items:baseline;padding:8px 14px;border-top:1px solid var(--border);background:var(--panel2)}
.dot{width:9px;height:9px;border-radius:50%;flex:0 0 auto;margin-top:5px}
.dot.healthy{background:var(--ok)} .dot.warning{background:var(--warn)}
.dot.critical{background:var(--crit)} .dot.unknown{background:var(--muted)}
.node .name{font-weight:600}
.node .ver{color:var(--accent);font-size:12px}
.node .meta{color:var(--muted);font-size:12px;margin-left:auto;text-align:right;max-width:55%}
.banner{background:var(--panel);border:1px solid var(--border);border-left:3px solid var(--crit);
  border-radius:8px;padding:10px 14px;margin-bottom:14px}
.banner.warn{border-left-color:var(--warn)}
.banner h3{margin:0 0 6px;font-size:13px} .banner li{font-size:13px;color:var(--muted)}
footer{color:var(--muted);font-size:12px;text-align:center;padding:24px}
.ro{font-size:12px;color:var(--ok);border:1px solid var(--ok);border-radius:6px;padding:2px 8px;margin-left:8px}
</style>
</head>
<body>
<header>
  <h1>InfraSight Report <span class="ro">READ-ONLY</span></h1>
  <div class="sub" id="subtitle"></div>
</header>
<div class="wrap">
  <div id="findings"></div>
  <div class="cards" id="cards"></div>
  <div class="controls">
    <input type="search" id="q" placeholder="Filter nodes by label, version or metadata…">
    <div class="types" id="types"></div>
  </div>
  <div id="groups"></div>
</div>
<footer>Generated by InfraSight · self-contained, offline-safe report</footer>

<script type="application/json" id="infrasight-data">
/*__INFRASIGHT_DATA__*/
</script>
<script>
(function(){
  var doc = JSON.parse(document.getElementById('infrasight-data').textContent);
  var RENDER_LIMIT = 400; // cap DOM nodes per type for responsiveness

  var s = doc.scan || {};
  document.getElementById('subtitle').textContent =
    (s.hostname||'unknown host') + '  ·  ' + (s.modules||[]).join(', ') +
    '  ·  ' + (s.durationMs||0) + 'ms  ·  v' + (s.version||'?');

  // summary cards
  var sum = doc.summary || {};
  var h = sum.healthSummary || {};
  var cards = [
    {l:'Nodes', n:sum.totalNodes||0, c:''},
    {l:'Edges', n:sum.totalEdges||0, c:''},
    {l:'Healthy', n:h.healthy||0, c:'ok'},
    {l:'Warning', n:h.warning||0, c:'warn'},
    {l:'Critical', n:h.critical||0, c:'crit'}
  ];
  document.getElementById('cards').innerHTML = cards.map(function(c){
    return '<div class="card '+c.c+'"><div class="n">'+c.n+'</div><div class="l">'+c.l+'</div></div>';
  }).join('');

  // findings banners
  var fEl = document.getElementById('findings'), fhtml='';
  if((sum.criticals||[]).length){
    fhtml += '<div class="banner"><h3>Critical findings</h3><ul>'+
      sum.criticals.map(function(x){return '<li>'+esc(x)+'</li>'}).join('')+'</ul></div>';
  }
  if((sum.warnings||[]).length){
    fhtml += '<div class="banner warn"><h3>Warnings</h3><ul>'+
      sum.warnings.map(function(x){return '<li>'+esc(x)+'</li>'}).join('')+'</ul></div>';
  }
  fEl.innerHTML = fhtml;

  // group nodes by type
  var groups = {};
  (doc.nodes||[]).forEach(function(n){ (groups[n.type]=groups[n.type]||[]).push(n); });
  var types = Object.keys(groups).sort();

  // type filter chips
  var active = {}; types.forEach(function(t){active[t]=true;});
  document.getElementById('types').innerHTML = types.map(function(t){
    return '<span class="chip" data-t="'+t+'">'+t+' ('+groups[t].length+')</span>';
  }).join('');
  document.getElementById('types').addEventListener('click', function(e){
    var c = e.target.closest('.chip'); if(!c) return;
    var t = c.getAttribute('data-t'); active[t]=!active[t];
    c.classList.toggle('off', !active[t]); render();
  });

  var q = document.getElementById('q');
  q.addEventListener('input', render);

  function render(){
    var term = q.value.trim().toLowerCase();
    var out = '';
    types.forEach(function(t){
      if(!active[t]) return;
      var items = groups[t].filter(function(n){ return matches(n, term); });
      if(!items.length) return;
      var shown = items.slice(0, RENDER_LIMIT);
      var rows = shown.map(function(n){
        var hp = n.health||'unknown';
        var meta = metaSummary(n);
        return '<div class="node"><span class="dot '+hp+'"></span>'+
          '<span class="name">'+esc(n.label)+'</span>'+
          (n.version?'<span class="ver">'+esc(n.version)+'</span>':'')+
          (meta?'<span class="meta">'+esc(meta)+'</span>':'')+'</div>';
      }).join('');
      var more = items.length>shown.length ?
        '<div class="node"><span class="meta">… and '+(items.length-shown.length)+' more</span></div>':'';
      out += '<details class="group" open><summary>'+t+
        '<span class="count">'+items.length+'</span></summary>'+rows+more+'</details>';
    });
    document.getElementById('groups').innerHTML = out || '<p style="color:var(--muted)">No nodes match.</p>';
  }

  function matches(n, term){
    if(!term) return true;
    if((n.label||'').toLowerCase().indexOf(term)>=0) return true;
    if((n.version||'').toLowerCase().indexOf(term)>=0) return true;
    return JSON.stringify(n.metadata||{}).toLowerCase().indexOf(term)>=0;
  }

  function metaSummary(n){
    var m = n.metadata||{}, keys = Object.keys(m).slice(0,3);
    return keys.map(function(k){return k+'='+m[k];}).join('  ');
  }

  function esc(s){ return String(s).replace(/[&<>"]/g, function(c){
    return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]; }); }

  render();
})();
</script>
</body>
</html>
`
